config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('user/', include('zanhu.user.urls', namespace="user")),
    path('', include('zanhu.tweet.urls', namespace="tweet")),
    path('chat/', include('zanhu.chat.urls')),
    path('post/', include('zanhu.post.urls', namespace='post')),
    path('froala_editor/', include('froala_editor.urls')),
    path('comment/', include('zanhu.comment.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zanhu/chat/urls.py
# -*- coding:utf8 -*-

from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

zanhu/post/urls.py
# -*- coding:utf8 -*-

from django.urls import path

from . import views

app_name = 'post'


urlpatterns = [
    path('add/', views.AddPost.as_view(), name='add_post'),
    path('<int:pk>/update/', views.UpdatePost.as_view(), name='update_post'),
    path('list', views.PostList.as_view(), name='post_list'),
    path('<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    path('drafts/', views.DraftListView.as_view(), name='draft_list'),
    path('delete/', views.DeletePostView.as_view(), name='delete_post'),
]

zanhu/tweet/urls.py
# -*- coding:utf8 -*-
from django.urls import path
from . import views

app_name = 'tweet'

urlpatterns = [
    path('', views.TweetListView.as_view(), name="index_page"),
    path('post_new_tweet', views.post_new_tweet, name='post_new_tweet'),
    path('delete/<str:pk>', views.TweetDeleteView.as_view(), name='delete_tweet'),
    path('like/', views.add_like, name='like_tweet'),
    path('comment/list/', views.get_comment_list, name='comment_list'),
    path('post_new_comment/', views.post_new_comment, name='post_new_comment'),
]

zanhu/user/urls.py
# -*- coding:utf8 -*-
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('<username>/', views.UserDetail.as_view(), name='detail_page'),
    path('<username>/setting/', views.UserUpdateDetail.as_view(), name='setting_page'),

]

zanhu/comment/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

COMMENT_MAX_LENGTH = getattr(settings, 'COMMENT_MAX_LENGTH', 3000)


# Create your models here.
class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, verbose_name='用户')
    content = models.TextField(_('评论内容'), max_length=COMMENT_MAX_LENGTH)
    submit_date = models.DateTimeField(verbose_name='提交时间', auto_now_add=True)
    is_removed = models.BooleanField(verbose_name='是否删除', default=False,
                                     help_text=_('检查评论是否被删除，否则 "此评论已经被删除" 消息会发送'))

    # Generic Relations
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    class Meta:
        ordering = ('-submit_date',)

    def __str__(self):
        return "%s..." % (self.content[:50])

zanhu/post/models.py
from django.db import models
from django.conf import settings
# Create your models here.
from froala_editor.fields import FroalaField
from django.contrib.contenttypes.fields import GenericRelation
from zanhu.comment.models import Comment


class Post(models.Model):
    """文章模型"""
    STATUS_CHOICES = (('D', '草稿'), ('P', '发表'),)
    title = models.CharField(max_length=255, verbose_name='标题')
    content = FroalaField(verbose_name='内容', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    updated = models.DateTimeField(auto_now=True, verbose_name='更新时间')
    status = models.CharField('文章状态', max_length=1, choices=STATUS_CHOICES, default='p')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                               verbose_name='作者')
    view_num = models.PositiveIntegerField(default=0, verbose_name='浏览次数')
    category = models.ForeignKey('Category', verbose_name='分类', on_delete=models.PROTECT, blank=True, null=True)
    tags = models.ManyToManyField('Tag', verbose_name='标签集合')
    comments = GenericRelation(Comment)

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name
        ordering = ['-created']

    def __str__(self):
        return self.title


class Category(models.Model):
    """文章分类"""
    name = models.CharField(verbose_name='分类名', max_length=10, unique=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    updated = models.DateTimeField(auto_now=True, verbose_name='更新时间')

    class Meta:
        verbose_name = "分类"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Tag(models.Model):
    """文章标签"""
    name = models.CharField(verbose_name='标签名', max_length=10, unique=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    updated = models.DateTimeField(auto_now=True, verbose_name='更新时间')

    class Meta:
        verbose_name = "标签"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

zanhu/tweet/models.py
# -*- coding:utf8 -*-
from django.db import models
import uuid
from django.conf import settings


# Create your models here.
class Tweet(models.Model):
    # uuid4 随机数生成
    uuid_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    # 发推的作者
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.SET_NULL,
                             related_name='publisher', verbose_name='用户')
    # 主推文，但reply为false时，自身就为评论
    parent = models.ForeignKey('self', blank=True, null=True, on_delete=models.CASCADE, related_name="thread",
                               verbose_name='自关联')
    # 推文或评论推文中的内容
    content = models.TextField(verbose_name='动态内容')
    # reply为TRUE就为推文的评论
    reply = models.BooleanField(default=False, verbose_name='是否为评论')
    # 点赞的用户，一条推文可以有很多赞，用户也可以点赞多个推文
    liked_user = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name='点赞用户',
                                        related_name='liked_user')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='更新时间')

    class Meta:
        verbose_name = '动态'
        verbose_name_plural = verbose_name
        ordering = ['-created_at']

    def __str__(self):
        return self.content

    def get_parent(self):
        """查找是否有父推文"""
        if self.parent:
            return self.parent
        else:
            return self

    def get_all_comment(self):
        """获取推文的所有评论"""
        parent = self.get_parent()
        return parent.thread.all()

    def comment_count(self):
        """获取推文的评论总数"""
        return self.get_all_comment().count()

    # def get_all_liked_user(self):
    #     return self.liked_user.all()
    #
    # def like_user_count(self):
    #     return self.liked_user.count()

    def switch_like(self, user):
        # 如果用户已经点赞过，则取消赞
        if user in self.liked_user.all():
            self.liked_user.remove(user)
        # 如果用户没有赞过，则添加赞
        else:
            self.liked_user.add(user)

    def tweet_comment(self, user, text):
        """
        评论推文
        :param user: 登录的用户
        :param text: 回复的内容
        :return: None
        """
        parent = self.get_parent()
        Tweet.objects.create(user=user, content=text,
                             reply=True, parent=parent,)

zanhu/user/models.py
# -*- coding:utf8 -*-
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from sorl.thumbnail import ImageField
# Create your models here.


class User(AbstractUser):
    """ 继承自AbstractUser """
    # 此类里面有很多字段和方法可以调用
    location = models.CharField(_('所在地'), max_length=50, null=True, blank=True)
    introduction = models.TextField(_('简介'), max_length=50, null=True, blank=True)
    picture = ImageField(_('头像'), upload_to='profile_pics/', null=True, blank=True)
    update_at = models.DateTimeField(_('更新时间'), auto_now=timezone.now, )
    gender_choices = (
        (u'M', u'男'),
        (u'F', u'女'),
    )
    gender = models.CharField(max_length=2, choices=gender_choices, null=True, blank=True)

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username

zanhu/chat/views.py
from django.shortcuts import render
from django.utils.safestring import mark_safe
import json

def index(request):
    return render(request, 'index.html', {})


def room(request, room_name):
    return render(request, 'room.html', {
        'room_name_json': mark_safe(json.dumps(room_name))
    })

zanhu/comment/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
# Create your views here.


def index(request):

    return HttpResponse('this is comment page')

zanhu/post/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from .models import Post
from .helper import increase_page_view, save_draft_redis
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponse


# Create your views here.
class AddPost(LoginRequiredMixin, CreateView):
    template_name = 'post/add.html'
    model = Post
    fields = ['title', 'content']
    success_url = '/post/list'

    def form_valid(self, form):
        if self.request.is_ajax():
            # ajax 保存文章草稿
            draft = save_draft_redis(self.request.user.pk,
                                     form.cleaned_data['title'],
                                     form.cleaned_data['content'])
            return JsonResponse(draft)
        else:
            f = form.save(commit=False)  # 传过来的form data不要保存
            f.author_id = self.request.user.pk  # 添加一个作者字段
            f.save()  # 保存form data
            response = super().form_valid(form)
            return response

    def form_invalid(self, form):
        response = super().form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        return response


class DraftListView(ListView):
    template_name = 'post/drafts_list.html'
    model = Post
    context_object_name = 'draft_post_list'

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user, status='D').order_by('-created')


class PostList(ListView):
    template_name = 'post/list.html'
    model = Post
    context_object_name = 'post_list'


class UpdatePost(LoginRequiredMixin, UpdateView):
    template_name = 'post/update.html'
    model = Post
    fields = ['title', 'content']

    def get_success_url(self):
        return reverse('post:post_detail', kwargs={'pk': self.kwargs['pk']})


class PostDetail(DetailView):
    template_name = 'post/detail.html'
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cache_view_num'] = increase_page_view(context['object'].pk)
        return context


class DeletePostView(DeleteView):
    model = Post
    success_url = '/post/list'

    def post(self, request, *args, **kwargs):
        if self.request.is_ajax():
            Post.objects.filter(id=self.request.POST['pk']).delete()
            return HttpResponse(status=200)
        return super().post(request, *args, **kwargs)

zanhu/tweet/views.py
# -*- coding:utf8 -*-
from .models import Tweet
from django.views.generic import ListView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from zanhu.tweet.util import ajax_required, AuthorRequireMixin
from django.shortcuts import render
from django.template.loader import render_to_string
from django.http import HttpResponseBadRequest, JsonResponse, HttpResponse
from django.urls import reverse_lazy


# Create your views here.
class TweetListView(LoginRequiredMixin, ListView):
    model = Tweet
    paginate_by = 20
    context_object_name = 'tweet_list'
    template_name = 'tweet/tweet_list.html'

    def get_queryset(self):
        return Tweet.objects.filter(reply=False)


@login_required
@ajax_required
@require_http_methods(['POST'])
def post_new_tweet(request):
    """发送动态，Ajax请求"""
    post_tweet = request.POST['content'].strip()
    if post_tweet:
        new_tweet = Tweet.objects.create(user=request.user, content=post_tweet)
        return render(request, template_name='tweet/single_tweet.html',
                      context={'tweet': new_tweet})
    else:
        return HttpResponseBadRequest('动态内容不能为空')


class TweetDeleteView(LoginRequiredMixin, AuthorRequireMixin, DeleteView):
    model = Tweet
    template_name = 'tweet/tweet_confirm_delete.html'
    slug_url_kwarg = 'slug'
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('tweet:index_page')


@login_required
@ajax_required
@require_http_methods(['POST'])
def add_like(request):
    """添加或删除点赞"""
    current_pk = request.POST['pk']
    if current_pk:
        current_tweet = Tweet.objects.get(pk=current_pk)
        current_tweet.switch_like(request.user)
        total_like = current_tweet.liked_user.count()
        return JsonResponse({'total_like': total_like})
    else:
        return HttpResponseBadRequest('当前PK值无效')


@login_required
@ajax_required
@require_http_methods(['GET'])
def get_comment_list(request):
    """GET请求方式获取评论"""
    current_pk = request.GET['pk']
    if current_pk:
        current_comments = Tweet.objects.filter(parent_id=current_pk)
        html = render_to_string("tweet/single_comment.html",
                                {"current_comments": current_comments})
        return JsonResponse({'html': html})
    else:
        return HttpResponseBadRequest('没有评论')


@login_required
@ajax_required
@require_http_methods(['POST'])
def post_new_comment(request):
    """发送动态，Ajax请求"""
    post_parent_id = request.POST['parent_id'].strip()
    post_content = request.POST['content'].strip()
    new_comment = Tweet.objects.create(user=request.user, content=post_content,
                                       parent_id=post_parent_id, reply=True)
    return HttpResponse('OK')

zanhu/user/views.py
# -*- coding:utf8 -*-
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import UpdateView
from django.views.generic import DetailView
from .models import User


# Create your views here.
class UserDetail(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'user/detail.html'
    slug_field = 'username'
    slug_url_kwarg = slug_field


class UserUpdateDetail(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'user/setting.html'
    slug_field = 'username'
    slug_url_kwarg = slug_field
    fields = ['gender', 'picture', 'introduction', 'location']

    def get_success_url(self):
        """更新成功后跳转到用户自己页面"""
        return reverse('user:setting_page', kwargs={'username': self.request.user.username})

zanhu/templates/base.html
{% load static %}
{% load thumbnail %}
<!DOCTYPE html>
<html>
<head>
    <title>赞 乎 - 玩一下自由</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/custom.css' %}" />
    <link rel="stylesheet" href="{% static 'css/iconfont.css' %}">
</head>
<body class="bg-light">
<nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm bg-light nav-underline">
    <div class="container">
      <a class="navbar-brand" href="{% url 'tweet:index_page' %}">赞 乎</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
              aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <form class="form-inline mr-auto   my-2 my-lg-0 order-md-1">
          <input class="form-control mr-sm-2" type="search" placeholder="Search">
        </form>
        <ul class="navbar-nav mt-2 mt-lg-0 order-md-0 mr-2" >
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'tweet:index_page' %}">动态 <span class="sr-only">(current)</span></a>
          </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'post:post_list' %}">专栏 <span class="sr-only">(current)</span></a>
          </li>
        </ul>
        {% if user.is_authenticated %}
        <ul class="navbar-nav ml-auto mt-2 mt-lg-0 order-md-2">
            <li class="nav-item d-flex align-items-center mr-3">{{ user.username }}</li>
          <li class="nav-item d-flex align-items-center">
                {% if user.picture %}
                    {% thumbnail user.picture "56x56" crop="center" as im %}
                        <a id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img class="navbar-avatar  rounded-circle" src="{{ im.url }}"
                             width="{{ im.width }}" height="{{ im.height }}">
                        </a>
                    {% endthumbnail %}
                {% else %}
                    <a id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
                       aria-expanded="false">
                        <img class="navbar-avatar  rounded-circle"
                             src="/media/profile_pics/default.jpg"  width="56" height="56">
                    </a>
                {% endif %}
                <div class="dropdown-menu dropdown-menu-right mr-5 shadow-sm border-0" aria-labelledby="dropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'post:add_post' %}">发表文章</a>
                    <a class="dropdown-item" href="{% url 'post:draft_list' %}">草稿箱</a>
                    <a class="dropdown-item" href="{% url 'user:detail_page' user.username %}">个人主页</a>
                    <a class="dropdown-item" href="{% url 'user:setting_page' user.username %}">账号设置</a>
                    <a class="dropdown-item" href="{% url 'account_logout' %}">登出</a>
                </div>
          </li>
        </ul>
        {% else %}
        <ul class="navbar-nav ml-auto mt-2 mt-lg-0 order-md-2">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'account_login' %}">登录</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_signup' %}">注册</a>
          </li>
        </ul>
        {% endif %}
      </div>
    </div>
</nav>


</main>

{%  block content %}
{% endblock %}

<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>
<script src="{% static 'js/tweet.js' %}" ></script>
</body>
</html>